from __future__ import annotations

import base64
import json
import os
import re
from typing import Any

import streamlit as st
from openai import OpenAI
import streamlit.components.v1 as components

APP_TITLE = "Creative Agent | Guided Venture & Campaign Workflow"
APP_HEADER = "Creative Agent"
SUPER_URL = "https://super.cycls.ai/"

# english and arabic templates of Step 1.
TEMPLATES = {
    "english": """## Problem
What are we trying to solve?

## User / Audience
Who is this for?

## Market / Geography
Which country / city / market matters most?

## Goal
What outcome matters most?

## Budget
What budget range do we have?

## Timeline
How quickly do we need to launch?

## Constraints
What must we avoid or respect?
""",
    "arabic": """## المشكلة
ما المشكلة التي نحاول حلّها؟

## المستخدم / الجمهور
لمن هذه الفكرة؟

## السوق / النطاق الجغرافي
ما الدولة / المدينة / السوق الأهم؟

## الهدف
ما النتيجة الأهم التي نريد تحقيقها؟

## الميزانية
ما نطاق الميزانية المتاح؟

## الجدول الزمني
ما السرعة المطلوبة للإطلاق؟

## القيود
ما الأمور التي يجب تجنبها أو احترامها؟
""",
}

# UI for English and Arabic.
TEXT = {
    "english": {
        "intro": "A guided workflow for choosing the right idea, not just generating ideas.\n\nFlow: define problem → generate 5 ideas → vote → shortlist 3 → compare → choose 1 → plan → handoff to Super.",
        "help": """### How this app works
1. Define the problem.
2. Generate 5 ideas from 5 creative ideators.
3. Let 5 evaluator agents vote, then shortlist 3 ideas.
4. Compare the 3 ideas on pros/cons, price signals, complexity, and rough money potential.
5. Let evaluators vote again, then choose 1 idea.
6. Generate an execution plan.
7. Hand off to Super.

At Step 2, Step 3, and Step 4 you can generate a fresh new Step 2 if you want a new direction.
""",
        "controls": "Controls",
        "language": "Language",
        "reset_workflow": "Reset workflow",
        "brief_template": "Brief template",
        "help_label": "Help",
        "missing_api_key": "Missing OPENAI_API_KEY. Add it in Streamlit Community Cloud → App settings → Secrets, or locally in `.streamlit/secrets.toml`.",
        "step1_title": "## Step 1 — Define the problem",
        "step1_intro": "I have your context. I only need a few missing details before I generate ideas.",
        "step1_answer_hint": "You can answer in one paragraph or paste the template below.",
        "step1_details": "Step 1 details",
        "step1_generate": "Generate Step 2",
        "step1_empty_error": "Please provide the problem context first.",
        "step1_more_detail": "I still need a little more detail before generating ideas.",
        "q1": "What product, service, campaign, or business problem are you working on?",
        "q2": "Who is the target audience and in which market or geography?",
        "q3": "What is the main goal you want to achieve?",
        "problem_summary": "**Problem summary:** {summary}",
        "problem_clear": "The problem is now defined clearly enough to move forward.",
        "step2_title": "## Step 2 — 5 ideas from 5 creative ideators",
        "generated_by": "**Generated by:** {value}",
        "one_liner": "**One-liner:** {value}",
        "why_work": "**Why it could work:**",
        "target_fit": "**Target fit:** {value}",
        "first_move": "**First move:** {value}",
        "evaluator_votes": "### Evaluator votes",
        "choose_three": "Choose exactly 3 ideas",
        "generate_new_step2": "Generate new Step 2",
        "continue_step3": "Continue to Step 3",
        "choose_three_error": "Please choose exactly 3 ideas.",
        "step3_title": "## Step 3 — Decide between the 3 shortlisted ideas",
        "advantages": "**Advantages**",
        "disadvantages": "**Disadvantages**",
        "price_search": "**Price search**",
        "build_launch": "- Build / launch: {value}",
        "competitor_market": "- Competitor / market: {value}",
        "media_distribution": "- Media / distribution: {value}",
        "tooling": "- Tooling: {value}",
        "complexity": "**Complexity:** {value}",
        "money_estimate": "**Rough money estimate:** {value}",
        "why_estimate": "**Why this estimate:** {value}",
        "risk_level": "**Risk level:** {value}",
        "choose_one": "Choose 1 final idea",
        "back_new_step2": "Back to new Step 2",
        "continue_step4": "Continue to Step 4",
        "step4_title": "## Step 4 — Plan",
        "step4_info": "If you do not like this direction, generate a brand-new Step 2 from the same Step 1 problem.",
        "step5_title": "## Step 5 — Delivery",
        "selected_idea": "**Selected idea:** {value}",
        "ready_super_prompt": "Ready-to-paste Super prompt",
        "copy_prompt": "Copy Prompt",
        "copied": "Copied!",
        "open_super": "Open Super",
        "recommended_flow": "<strong>Recommended flow:</strong> click <strong>Copy Prompt</strong>, then <strong>Open Super</strong>, paste, and press Enter.",
        "auto_copy": "<em>The prompt is auto-copied again when you click Open Super.</em>",
    },
    "arabic": {
        "intro": "مسار عمل موجّه لاختيار الفكرة المناسبة، وليس فقط توليد أفكار.\n\nالمسار: تحديد المشكلة ← توليد 5 أفكار ← تصويت ← اختيار 3 أفكار ← مقارنة ← اختيار فكرة واحدة ← خطة ← تسليم إلى Super.",
        "help": """### كيف يعمل هذا التطبيق
1. حدّد المشكلة.
2. ولّد 5 أفكار من 5 شخصيات إبداعية.
3. تصوّت 5 شخصيات تقييم، ثم تختار 3 أفكار.
4. نقارن بين الأفكار الثلاث من حيث المزايا والعيوب ومؤشرات السعر والتعقيد والعائد التقريبي.
5. تصوّت شخصيات التقييم مرة أخرى، ثم تختار فكرة واحدة.
6. نولّد خطة تنفيذ.
7. نجهّز التسليم إلى Super.

في الخطوة 2 والخطوة 3 والخطوة 4 يمكنك توليد خطوة 2 جديدة إذا أردت اتجاهًا مختلفًا.
""",
        "controls": "التحكم",
        "language": "اللغة",
        "reset_workflow": "إعادة ضبط المسار",
        "brief_template": "قالب الملخص",
        "help_label": "مساعدة",
        "missing_api_key": "مفتاح OPENAI_API_KEY مفقود. أضِفه في إعدادات Streamlit Community Cloud → Secrets أو محليًا داخل `.streamlit/secrets.toml`.",
        "step1_title": "## الخطوة 1 — تحديد المشكلة",
        "step1_intro": "فهمت السياق. أحتاج فقط إلى بعض التفاصيل الإضافية قبل أن أبدأ توليد الأفكار.",
        "step1_answer_hint": "يمكنك الإجابة في فقرة واحدة أو لصق القالب التالي.",
        "step1_details": "تفاصيل الخطوة 1",
        "step1_generate": "ولّد الخطوة 2",
        "step1_empty_error": "يرجى إدخال تفاصيل المشكلة أولًا.",
        "step1_more_detail": "ما زلت أحتاج إلى بعض التفاصيل الإضافية قبل توليد الأفكار.",
        "q1": "ما المنتج أو الخدمة أو الحملة أو المشكلة التجارية التي تعمل عليها؟",
        "q2": "من هو الجمهور المستهدف وفي أي سوق أو نطاق جغرافي؟",
        "q3": "ما الهدف الرئيسي الذي تريد تحقيقه؟",
        "problem_summary": "**ملخص المشكلة:** {summary}",
        "problem_clear": "أصبحت المشكلة واضحة بما يكفي للانتقال إلى المرحلة التالية.",
        "step2_title": "## الخطوة 2 — 5 أفكار من 5 شخصيات إبداعية",
        "generated_by": "**تم توليدها بواسطة:** {value}",
        "one_liner": "**وصف مختصر:** {value}",
        "why_work": "**لماذا قد تنجح؟**",
        "target_fit": "**ملاءمة الجمهور:** {value}",
        "first_move": "**أول خطوة:** {value}",
        "evaluator_votes": "### تصويت المقيمين",
        "choose_three": "اختر 3 أفكار بالضبط",
        "generate_new_step2": "ولّد خطوة 2 جديدة",
        "continue_step3": "انتقل إلى الخطوة 3",
        "choose_three_error": "يرجى اختيار 3 أفكار بالضبط.",
        "step3_title": "## الخطوة 3 — اتخاذ القرار بين الأفكار الثلاث المختارة",
        "advantages": "**المزايا**",
        "disadvantages": "**العيوب**",
        "price_search": "**بحث الأسعار**",
        "build_launch": "- تكلفة البناء / الإطلاق: {value}",
        "competitor_market": "- السوق / المنافسون: {value}",
        "media_distribution": "- الإعلام / التوزيع: {value}",
        "tooling": "- الأدوات: {value}",
        "complexity": "**التعقيد:** {value}",
        "money_estimate": "**التقدير المالي التقريبي:** {value}",
        "why_estimate": "**سبب هذا التقدير:** {value}",
        "risk_level": "**مستوى المخاطرة:** {value}",
        "choose_one": "اختر فكرة نهائية واحدة",
        "back_new_step2": "العودة إلى خطوة 2 جديدة",
        "continue_step4": "انتقل إلى الخطوة 4",
        "step4_title": "## الخطوة 4 — الخطة",
        "step4_info": "إذا لم يعجبك هذا الاتجاه، يمكنك توليد خطوة 2 جديدة من نفس مشكلة الخطوة 1.",
        "step5_title": "## الخطوة 5 — التسليم",
        "selected_idea": "**الفكرة المختارة:** {value}",
        "ready_super_prompt": "النص الجاهز للنسخ إلى Super",
        "copy_prompt": "انسخ النص",
        "copied": "تم النسخ!",
        "open_super": "افتح Super",
        "recommended_flow": "<strong>الطريقة الموصى بها:</strong> اضغط <strong>انسخ النص</strong> ثم <strong>افتح Super</strong> ثم الصق النص واضغط Enter.",
        "auto_copy": "<em>سيتم نسخ النص مرة أخرى تلقائيًا عند الضغط على Open Super.</em>",
    },
}

# These agents vote and evaluate ideas from different business perspectives.
EVALUATOR_AGENTS = [
    "Strategist",
    "Creative Director",
    "Performance Marketer",
    "Brand Builder",
    "Operator / Feasibility Reviewer",
]

# These agents generate the five different creative directions in Step 2.
IDEATION_AGENTS = [
    "Trend Hunter",
    "Cultural Storyteller",
    "Campaign Provocateur",
    "Social Native Creator",
    "Experience Designer",
]

#Intro for the model so he respond in the good language
LANGUAGE_GUIDE = {
    "english": "Write the full response in English.",
    "arabic": "Write the full response in Arabic. Use clear modern Arabic; Saudi flavor is welcome when helpful.",
}

# Return a translated UI (specificaly for Arabic see the variable TEXT line 65)
def tr(key: str, **kwargs: Any) -> str:
    lang = st.session_state.get("language", "english") if hasattr(st, "session_state") else "english"
    text = TEXT.get(lang, TEXT["english"]).get(key, TEXT["english"].get(key, key))
    return text.format(**kwargs) if kwargs else text

# Return the current Step 1 template based on the selected language.
def current_template() -> str:
    lang = st.session_state.get("language", "english") if hasattr(st, "session_state") else "english"
    return TEMPLATES.get(lang, TEMPLATES["english"])


def is_arabic() -> bool:
    return st.session_state.get("language", "english") == "arabic"


def _get_api_key() -> str | None:
    try:
        return st.secrets.get("OPENAI_API_KEY")
    except Exception:
        return os.getenv("OPENAI_API_KEY")


def _client() -> OpenAI:
    api_key = _get_api_key()
    if not api_key:
        raise RuntimeError("Missing OPENAI_API_KEY. Add it in Streamlit secrets or environment variables.")
    return OpenAI(api_key=api_key)

# Choose the model from secrets or environment, with as default gpt-5.4-mini.
def _model() -> str:
    try:
        return st.secrets.get("OPENAI_MODEL", os.getenv("OPENAI_MODEL", "gpt-5.4-mini"))
    except Exception:
        return os.getenv("OPENAI_MODEL", "gpt-5.4-mini")

# Send a prompt to the model and return text , can do web search
def _response_text(prompt: str, *, use_web_search: bool = False) -> str:
    kwargs: dict[str, Any] = {
        "model": _model(),
        "input": prompt,
    }
    if use_web_search:
        kwargs["tools"] = [{"type": "web_search_preview"}]
    response = _client().responses.create(**kwargs)
    output_text = getattr(response, "output_text", None)
    if output_text:
        return output_text
    raise RuntimeError("Model did not return output_text.")

#Extract JSON from a model response
def _extract_json(text: str) -> Any:
    text = text.strip()
    if not text:
        raise ValueError("Empty model output.")
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    fenced = re.search(r"```(?:json)?\s*(\{.*\}|\[.*\])\s*```", text, re.DOTALL)
    if fenced:
        return json.loads(fenced.group(1))

    starts = [i for i, ch in enumerate(text) if ch in "[{"]
    for start in starts:
        for end in range(len(text), start, -1):
            chunk = text[start:end]
            try:
                return json.loads(chunk)
            except json.JSONDecodeError:
                continue
    raise ValueError(f"Could not parse JSON from model output:\n{text[:1000]}")

#get model output and parse it into Python data.
def _response_json(prompt: str, *, use_web_search: bool = False) -> Any:
    return _extract_json(_response_text(prompt, use_web_search=use_web_search))


def _language_line(language: str) -> str:
    return LANGUAGE_GUIDE.get(language, LANGUAGE_GUIDE["english"])

# Prompt for Step 1: decide whether the response is complete enough to move to step 2 idea generation.
def _problem_analysis_prompt(message: str, language: str) -> str:
    return f"""
You are checking whether the user gave enough detail to define a business / campaign / product problem.
{_language_line(language)}

Return JSON only with this exact shape:
{{
  "is_complete": true or false,
  "summary": "normalized 3-6 line problem brief",
  "missing_details": ["short missing detail question", "..."],
  "next_step_message": "a short user-facing message"
}}

Be permissive.
Move to idea generation whenever you can make reasonable assumptions.
Do NOT restart the intake just because one or two details are fuzzy.
Only keep is_complete=false if a missing detail would materially change the ideas.
In most cases, proceed when you know:
- what kind of product / offer this is at a broad level
- the audience
- the market / geography
- the main goal
If budget, timeline, channel, or exact age band are fuzzy, usually proceed and make explicit assumptions.
If a user adds more detail after an earlier incomplete answer, treat it as additive context, not a new problem.
Ask for at most 3 focused missing details.

User input / accumulated context:
{message}
""".strip()

# Prompt for Step 2
def _generate_ideas_prompt(state: dict[str, Any]) -> str:
    return f"""
You are running Step 2 of a guided ideation workflow.
{_language_line(state['language'])}

Problem brief:
{state['problem_brief']}

Generate exactly 5 ideas, each created by a different ideation persona:
{json.dumps(IDEATION_AGENTS, ensure_ascii=False)}

Return JSON only with this exact shape:
{{
  "problem_summary": "short summary",
  "ideas": [
    {{
      "id": 1,
      "generator": "one of the 5 ideation personas",
      "name": "idea name",
      "one_liner": "single sentence",
      "why_it_could_work": ["point", "point"],
      "target_fit": "why this fits the audience",
      "first_move": "what we would do first"
    }}
  ]
}}

Rules:
- Make the 5 ideas genuinely different.
- Think like 5 creative people, not one person with 5 minor rewrites.
- Keep each idea practical enough to test.
- If the problem is in Arabic, stay naturally Arabic-first.
""".strip()

# Prompt for the first voting round: each evaluator agent selects the top two ideas.
def _vote_top_two_prompt(state: dict[str, Any]) -> str:
    return f"""
You are running the evaluator vote for Step 2.
{_language_line(state['language'])}

Problem brief:
{state['problem_brief']}

Ideas:
{json.dumps(state['ideas'], ensure_ascii=False, indent=2)}

Evaluators:
{json.dumps(EVALUATOR_AGENTS, ensure_ascii=False)}

Return JSON only:
{{
  "votes": [
    {{
      "evaluator": "Strategist",
      "top_two": [1, 3],
      "reason": "short reason"
    }}
  ]
}}
""".strip()

#Prompt for Step 3: compare the three shortlisted ideas on business and execution criteria.
def _compare_shortlist_prompt(state: dict[str, Any]) -> str:
    shortlisted = [idea for idea in state["ideas"] if idea["id"] in state["shortlisted"]]
    return f"""
You are running Step 3: compare 3 shortlisted ideas.
{_language_line(state['language'])}

Problem brief:
{state['problem_brief']}

Shortlisted ideas:
{json.dumps(shortlisted, ensure_ascii=False, indent=2)}

Do light web-informed reasoning for price / cost / competitor signals when useful.
Give simple rough estimates, not finance-grade models.
Interpret "search price" broadly:
- likely build / launch cost
- relevant competitor or category pricing signals
- likely media / ad cost signals
- tooling / implementation cost signals if relevant

Return JSON only with this exact shape:
{{
  "comparisons": [
    {{
      "id": 1,
      "name": "idea name",
      "advantages": ["point", "point"],
      "disadvantages": ["point", "point"],
      "price_search": {{
        "build_cost_signal": "rough range with short note",
        "competitor_or_market_signal": "rough range with short note",
        "media_or_distribution_signal": "rough range with short note",
        "tooling_signal": "rough range with short note"
      }},
      "complexity": "Low / Medium / High",
      "money_estimate": "simple rough money potential estimate",
      "why_money_estimate": "1-2 short sentences",
      "risk_level": "Low / Medium / High"
    }}
  ]
}}
""".strip()

# Prompt for the final voting round: each evaluator chooses the single best shortlisted idea.
def _vote_best_prompt(state: dict[str, Any]) -> str:
    return f"""
You are running the evaluator vote for Step 3.
{_language_line(state['language'])}

Problem brief:
{state['problem_brief']}

Comparisons:
{json.dumps(state['comparisons'], ensure_ascii=False, indent=2)}

Evaluators:
{json.dumps(EVALUATOR_AGENTS, ensure_ascii=False)}

Return JSON only:
{{
  "votes": [
    {{
      "evaluator": "Strategist",
      "best": 2,
      "reason": "short reason"
    }}
  ]
}}
""".strip()

# Prompt for Step 4: generate an execution plan for the chosen idea.
def _plan_prompt(state: dict[str, Any]) -> str:
    chosen = state.get("selected_idea") or {}
    comparison = next((x for x in state["comparisons"] if x.get("id") == chosen.get("id")), {})
    return f"""
You are running Step 4: build the execution plan.
{_language_line(state['language'])}

Problem brief:
{state['problem_brief']}

Chosen idea:
{json.dumps(chosen, ensure_ascii=False, indent=2)}

Comparison notes:
{json.dumps(comparison, ensure_ascii=False, indent=2)}

Write a clear markdown plan with these sections:
1. Selected idea
2. Why this idea won
3. Goal
4. Success metrics
5. 30-day execution plan
6. Team / roles needed
7. Budget buckets
8. Biggest risks + mitigation
9. First 3 actions to do this week

Keep it practical and operator-ready.
""".strip()

# Build the final prompt that the user can paste into Super.
def _super_prompt(state: dict[str, Any]) -> str:
    chosen = state.get("selected_idea") or {}
    comparison = next((x for x in state["comparisons"] if x.get("id") == chosen.get("id")), {})
    return f"""
You are my execution agent. Start working immediately on this chosen idea.

Problem brief:
{state['problem_brief']}

Chosen idea:
{json.dumps(chosen, ensure_ascii=False, indent=2)}

Decision notes:
{json.dumps(comparison, ensure_ascii=False, indent=2)}

Execution plan:
{state['plan_markdown']}

Your job now:
1. Turn this into a concrete work plan.
2. Break it into milestones and tasks.
3. Identify assumptions that must be validated first.
4. Produce the first deliverables needed to start execution immediately.
5. Be proactive and practical.

Start with:
- a concise execution summary
- the first milestone
- the first 5 tasks in priority order
""".strip()

# Count how many votes each idea received in a given round.
def _count_votes(vote_payload: list[dict[str, Any]], key: str) -> dict[int, int]:
    counts: dict[int, int] = {}
    for item in vote_payload:
        for idx in item.get(key, []):
            counts[idx] = counts.get(idx, 0) + 1
    return counts


def _init_state() -> None:
    defaults = {
        "language": "english",
        "stage": "define_problem",
        "problem_summary": "",
        "problem_brief": "",
        "raw_problem_input": "",
        "missing_details": [],
        "ideas": [],
        "round1_votes": {},
        "round1_reasoning": [],
        "shortlisted": [],
        "comparisons": [],
        "round2_votes": {},
        "round2_reasoning": [],
        "selected_idea": None,
        "plan_markdown": "",
        "super_prompt": "",
        "step1_answer": "",
        "error": "",
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


def _reset_workflow(keep_language: bool = True) -> None:
    language = st.session_state.get("language", "english") if keep_language else "english"
    for k in list(st.session_state.keys()):
        if k.startswith("select_"):
            del st.session_state[k]
    _init_state()
    st.session_state.language = language
    st.session_state.stage = "define_problem"
    st.session_state.problem_summary = ""
    st.session_state.problem_brief = ""
    st.session_state.raw_problem_input = ""
    st.session_state.missing_details = []
    st.session_state.ideas = []
    st.session_state.round1_votes = {}
    st.session_state.round1_reasoning = []
    st.session_state.shortlisted = []
    st.session_state.comparisons = []
    st.session_state.round2_votes = {}
    st.session_state.round2_reasoning = []
    st.session_state.selected_idea = None
    st.session_state.plan_markdown = ""
    st.session_state.super_prompt = ""
    st.session_state.step1_answer = ""
    st.session_state.error = ""


# Regenerate a new Step 2
def _regenerate_step2() -> None:
    state = st.session_state
    ideas_payload = _response_json(_generate_ideas_prompt(state))
    state.problem_summary = ideas_payload.get("problem_summary", state.problem_summary)
    state.ideas = ideas_payload.get("ideas", [])
    vote_payload = _response_json(_vote_top_two_prompt(state))
    state.round1_reasoning = vote_payload.get("votes", [])
    state.round1_votes = _count_votes(state.round1_reasoning, "top_two")
    state.shortlisted = []
    state.comparisons = []
    state.round2_votes = {}
    state.round2_reasoning = []
    state.selected_idea = None
    state.plan_markdown = ""
    state.super_prompt = ""
    state.stage = "choose_three"

# Render the Step 5
def _copy_open_html(prompt: str) -> str:
    encoded = base64.b64encode(prompt.encode("utf-8")).decode("ascii")
    text_align = "right" if is_arabic() else "left"
    return f'''<div style="display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:8px 0 12px 0;justify-content:{'flex-end' if is_arabic() else 'flex-start'};">
  <button onclick="navigator.clipboard.writeText(atob('{encoded}')).then(() => this.innerText='{tr('copied')}')" style="padding:10px 16px;border:none;border-radius:10px;background:#10a37f;color:white;font-weight:600;cursor:pointer;">{tr('copy_prompt')}</button>
  <a href="{SUPER_URL}" target="_blank" rel="noopener noreferrer" onclick="navigator.clipboard.writeText(atob('{encoded}'))" style="padding:10px 16px;border-radius:10px;background:#2563eb;color:white;text-decoration:none;font-weight:600;display:inline-block;">{tr('open_super')}</a>
</div>
<p style="color:#e5e7eb;text-align:{text_align};">{tr('recommended_flow')}</p>
<p style="color:#9ca3af;text-align:{text_align};">{tr('auto_copy')}</p>'''

# Render the idea list, first-round votes, shortlist controls, and Step 2 actions
def _render_step2() -> None:
    st.markdown(tr("step1_title"))
    st.markdown(tr("problem_summary", summary=st.session_state.problem_summary))
    st.info(tr("problem_clear"))
    st.markdown(tr("step2_title"))
    for idea in sorted(st.session_state.ideas, key=lambda x: x["id"]):
        with st.container(border=True):
            st.markdown(f"### {idea['id']}) {idea['name']} — {st.session_state.round1_votes.get(idea['id'], 0)} vote(s)")
            st.markdown(tr("generated_by", value=idea["generator"]))
            st.markdown(tr("one_liner", value=idea["one_liner"]))
            st.markdown(tr("why_work"))
            for point in idea.get("why_it_could_work", []):
                st.markdown(f"- {point}")
            st.markdown(tr("target_fit", value=idea.get("target_fit", "")))
            st.markdown(tr("first_move", value=idea.get("first_move", "")))

    st.markdown(tr("evaluator_votes"))
    for vote in st.session_state.round1_reasoning:
        st.markdown(f"- **{vote['evaluator']}** → {vote['top_two']} — {vote['reason']}")

    c1, c2 = st.columns([2, 1])
    with c1:
        picks = st.multiselect(
            tr("choose_three"),
            options=[idea["id"] for idea in st.session_state.ideas],
            format_func=lambda n: next(i["name"] for i in st.session_state.ideas if i["id"] == n),
            key="select_three",
        )
    with c2:
        st.markdown("<br>", unsafe_allow_html=True)
        if st.button(tr("generate_new_step2"), use_container_width=True):
            _regenerate_step2()
            st.rerun()

    if st.button(tr("continue_step3"), type="primary"):
        if len(picks) != 3:
            st.error(tr("choose_three_error"))
        else:
            st.session_state.shortlisted = picks
            comparison_payload = _response_json(_compare_shortlist_prompt(st.session_state), use_web_search=True)
            st.session_state.comparisons = comparison_payload.get("comparisons", [])
            vote_payload = _response_json(_vote_best_prompt(st.session_state))
            st.session_state.round2_reasoning = vote_payload.get("votes", [])
            st.session_state.round2_votes = _count_votes([
                {"best": [item.get("best")]} for item in st.session_state.round2_reasoning if item.get("best") is not None
            ], "best")
            st.session_state.stage = "choose_one"
            st.rerun()

# Render the comparison view, final choice controls, and the option to go back to a new Step 2
def _render_step3() -> None:
    st.markdown(tr("step3_title"))
    for comp in st.session_state.comparisons:
        with st.container(border=True):
            st.markdown(f"### {comp['id']}) {comp['name']} — {st.session_state.round2_votes.get(comp['id'], 0)} vote(s)")
            st.markdown(tr("advantages"))
            for item in comp.get("advantages", []):
                st.markdown(f"- {item}")
            st.markdown(tr("disadvantages"))
            for item in comp.get("disadvantages", []):
                st.markdown(f"- {item}")
            price = comp.get("price_search", {})
            st.markdown(tr("price_search"))
            st.markdown(tr("build_launch", value=price.get("build_cost_signal", "")))
            st.markdown(tr("competitor_market", value=price.get("competitor_or_market_signal", "")))
            st.markdown(tr("media_distribution", value=price.get("media_or_distribution_signal", "")))
            st.markdown(tr("tooling", value=price.get("tooling_signal", "")))
            st.markdown(tr("complexity", value=comp.get("complexity", "")))
            st.markdown(tr("money_estimate", value=comp.get("money_estimate", "")))
            st.markdown(tr("why_estimate", value=comp.get("why_money_estimate", "")))
            st.markdown(tr("risk_level", value=comp.get("risk_level", "")))

    st.markdown(tr("evaluator_votes"))
    for vote in st.session_state.round2_reasoning:
        st.markdown(f"- **{vote['evaluator']}** → Idea {vote['best']} — {vote['reason']}")

    c1, c2 = st.columns([2, 1])
    with c1:
        choice = st.selectbox(
            tr("choose_one"),
            options=[c["id"] for c in st.session_state.comparisons],
            format_func=lambda n: next(c["name"] for c in st.session_state.comparisons if c["id"] == n),
            key="select_one",
        )
    with c2:
        st.markdown("<br>", unsafe_allow_html=True)
        if st.button(tr("back_new_step2"), use_container_width=True):
            _regenerate_step2()
            st.rerun()

    if st.button(tr("continue_step4"), type="primary"):
        st.session_state.selected_idea = next((idea for idea in st.session_state.ideas if idea["id"] == choice), None)
        st.session_state.plan_markdown = _response_text(_plan_prompt(st.session_state))
        st.session_state.super_prompt = _super_prompt(st.session_state)
        st.session_state.stage = "delivered"
        st.rerun()


# Render the execution plan and step 5
def _render_step4_and_5() -> None:
    st.markdown(tr("step4_title"))
    st.markdown(st.session_state.plan_markdown)
    c1, c2 = st.columns([1, 2])
    with c1:
        if st.button(tr("back_new_step2"), use_container_width=True):
            _regenerate_step2()
            st.rerun()
    with c2:
        st.info(tr("step4_info"))

    st.markdown(tr("step5_title"))
    st.markdown(tr("selected_idea", value=(st.session_state.selected_idea or {}).get("name", "N/A")))
    components.html(_copy_open_html(st.session_state.super_prompt), height=140)
    st.text_area(tr("ready_super_prompt"), st.session_state.super_prompt, height=320)
    st.link_button(tr("open_super"), SUPER_URL)


def _inject_language_css() -> None:
    if is_arabic():
        st.markdown(
            """
            <style>
            html, body, [data-testid="stAppViewContainer"] { direction: rtl; }
            [data-testid="stSidebar"] * { text-align: right; }
            [data-testid="stAppViewContainer"] .stMarkdown, 
            [data-testid="stAppViewContainer"] label,
            [data-testid="stAppViewContainer"] p,
            [data-testid="stAppViewContainer"] h1,
            [data-testid="stAppViewContainer"] h2,
            [data-testid="stAppViewContainer"] h3,
            [data-testid="stAppViewContainer"] li,
            [data-testid="stAppViewContainer"] div { text-align: right; }
            </style>
            """,
            unsafe_allow_html=True,
        )


def main() -> None:
    st.set_page_config(page_title=APP_TITLE, page_icon="💡", layout="wide")
    _init_state()
    _inject_language_css()

    st.title(APP_HEADER)
    st.write(tr("intro"))

    with st.sidebar:
        st.header(tr("controls"))
        language = st.selectbox(
            tr("language"),
            ["english", "arabic"],
            index=["english", "arabic"].index(st.session_state.language if st.session_state.language in ["english", "arabic"] else "english"),
        )
        if language != st.session_state.language:
            st.session_state.language = language
            st.rerun()
        if st.button(tr("reset_workflow"), use_container_width=True):
            _reset_workflow()
            st.rerun()
        with st.expander(tr("brief_template")):
            st.code(current_template())
        with st.expander(tr("help_label")):
            st.markdown(tr("help"))

    api_key = _get_api_key()
    if not api_key:
        st.error(tr("missing_api_key"))
        st.code('OPENAI_API_KEY = "your_key_here"')
        return

    try:
        if st.session_state.stage == "define_problem":
            st.markdown(tr("step1_title"))
            st.markdown(tr("step1_intro"))

            missing = st.session_state.missing_details or [tr("q1"), tr("q2"), tr("q3")]
            for i, q in enumerate(missing[:5], start=1):
                st.markdown(f"{i}. {q}")

            st.markdown(tr("step1_answer_hint"))

            user_problem = st.text_area(
                tr("step1_details"),
                value=st.session_state.step1_answer,
                height=220,
                placeholder=current_template(),
            )
            st.session_state.step1_answer = user_problem

            if st.button(tr("step1_generate"), type="primary"):
                if not user_problem.strip():
                    st.error(tr("step1_empty_error"))
                else:
                    if st.session_state.raw_problem_input:
                        combined_input = (
                            f"{st.session_state.raw_problem_input}\n\nAdditional user input:\n{user_problem.strip()}"
                        )
                    else:
                        combined_input = user_problem.strip()

                    analysis = _response_json(
                        _problem_analysis_prompt(combined_input, st.session_state.language)
                    )

                    st.session_state.raw_problem_input = combined_input
                    st.session_state.problem_summary = analysis.get("summary", "")
                    st.session_state.problem_brief = analysis.get("summary", "") or combined_input
                    st.session_state.missing_details = analysis.get("missing_details", [])

                    if not analysis.get("is_complete", False):
                        st.warning(tr("step1_more_detail"))
                    else:
                        _regenerate_step2()
                        st.rerun()
            return

        if st.session_state.stage == "choose_three":
            _render_step2()
            return

        if st.session_state.stage == "choose_one":
            _render_step3()
            return

        if st.session_state.stage == "delivered":
            _render_step4_and_5()
            return

    except Exception as exc:
        st.error(f"Something went wrong: {exc}")


if __name__ == "__main__":
    main()
